import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import "./globals.css";

export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="w-[100vw] h-[100vh] overflow-scroll no-scrollbar">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
